version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'OnlineElectronicsStore'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'rootpass'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  eureka-server:
    image: springcloud/eureka
    ports:
      - "8761:8761"
    networks:
      - backend

  products-service:
    build: ./productsService
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - backend

  cart-service:
    build: ./cartService
    ports:
      - "8082:8082"
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - backend

  review-service:
    build: ./reviewService
    ports:
      - "8083:8083"
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - backend

  api-gateway:
    build: ./apiGateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
