version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'OnlineElectronicsStore'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'rootpass'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  eureka-server:
    image: openjdk:17-jdk-slim
    ports:
      - "8761:8761"
    networks:
      - backend
    command: ["java", "-jar", "/app/eureka/eureka-server.jar"]
    volumes:
      - ./eureka/build/libs/eureka.jar:/app/eureka/eureka-server.jar

  products-service:
    image: openjdk:17-jdk-slim
    ports:
      - "8081:8081"
    depends_on:
      - mysql-db
      - eureka-server
    environment:
       - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    networks:
      - backend
    command: ["java", "-jar", "/app/productsService/productsService.jar"]
    volumes:
      - ./productsService/build/libs/productsService.jar:/app/productsService/productsService.jar

  cart-service:
    image: openjdk:17-jdk-slim
    ports:
      - "8082:8082"
    depends_on:
      - mysql-db
      - eureka-server
    environment:
       - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    command: ["java", "-jar", "/app/cartService/cartService.jar"]
    volumes:
      - ./cartService/build/libs/cartService.jar:/app/cartService/cartService.jar
    networks:
      - backend

  review-service:
    image: openjdk:17-jdk-slim
    ports:
      - "8083:8083"
    depends_on:
      - mysql-db
      - eureka-server
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
    command: ["java", "-jar", "/app/reviewService/reviewService.jar"]
    volumes:
      - ./reviewService/build/libs/reviewService.jar:/app/reviewService/reviewService.jar
    networks:
      - backend

  api-gateway:
    image: openjdk:17-jdk-slim
    ports:
      - "8080:8080"
    networks:
      - backend
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/

    command: ["java", "-jar", "/app/apiGateway/apiGateway.jar"]
    links:
      - eureka-server
    depends_on:
      - eureka-server
      - products-service
      - cart-service
      - review-service
    volumes:
      - ./apiGateway/build/libs/gateway.jar:/app/apiGateway/apiGateway.jar

networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
