spring:
  cloud:
    gateway:
      routes:
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/products/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/reviews/**
  application:
    name: api-gateway
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8080

