spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://localhost:3306/OnlineElectronicsStore
    username: user
    password: pass

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

